# Generated by Django 5.0.6 on 2024-05-19 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shader',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shader_id', models.CharField(default='shader_id', max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('username', models.CharField(max_length=200)),
            ],
        ),
    ]
