# Generated by Django 5.0.6 on 2024-05-19 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaderator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renderpass',
            fields=[
                ('renderpass_id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('shader_id', models.ForeignKey(default='shader_id', on_delete=django.db.models.deletion.CASCADE, to='shaderator.shader')),
            ],
        ),
    ]
