# Generated by Django 5.0.6 on 2024-05-21 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaderator', '0002_renderpass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fetch_Errors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shader_id', models.ForeignKey(default='shader_id', on_delete=django.db.models.deletion.CASCADE, to='shaderator.shader')),
            ],
        ),
    ]
