# Generated by Django 5.0.6 on 2024-06-06 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaderator', '0003_fetch_errors'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedShaderCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
