# Generated by Django 5.0.6 on 2024-06-06 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaderator', '0004_generatedshadercode'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedshadercode',
            name='prompt',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
