# Generated by Django 5.0.6 on 2024-07-21 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaderator', '0005_generatedshadercode_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedShaderCodeView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('code', models.TextField()),
            ],
            options={
                'db_table': 'shaderator_generatedshadercode_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShadescriptorCorpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human_prompt', models.TextField()),
                ('code', models.TextField()),
                ('shader_id', models.ForeignKey(default='shader_id', on_delete=django.db.models.deletion.CASCADE, to='shaderator.shader')),
            ],
        ),
    ]
