# Generated by Django 5.0.6 on 2024-07-21 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaderator', '0006_generatedshadercodeview_shadescriptorcorpus'),
    ]

    operations = [
        migrations.CreateModel(
            name='SandboxGLSLCorpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synth_prompt', models.TextField()),
                ('code', models.TextField()),
                ('vector', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='shadescriptorcorpus',
            name='vector',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shadescriptorcorpus',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shadescriptorcorpus',
            name='shader_id',
            field=models.CharField(max_length=10),
        ),
    ]
