# Generated by Django 5.0.6 on 2024-08-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaderator', '0007_sandboxglslcorpus_shadescriptorcorpus_vector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedshadercode',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedshadercode',
            name='vector',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
