# Generated by Django 5.0.6 on 2024-08-11 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaderator', '0008_generatedshadercode_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Session',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_key', models.CharField(max_length=40)),
                ('shader_familiarity', models.BooleanField(null=True)),
                ('cscience_familiarity', models.BooleanField(null=True)),
                ('programming_familiarity', models.BooleanField(null=True)),
                ('new_media_familiarity', models.BooleanField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='shadescriptorcorpus',
            name='input_date',
            field=models.DateTimeField(null=True, verbose_name='date of input'),
        ),
        migrations.AddField(
            model_name='shadescriptorcorpus',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shaderator.user_session'),
        ),
    ]
