# Generated by Django 5.0.6 on 2024-08-26 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaderator', '0009_user_session_shadescriptorcorpus_input_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True)),
                ('vector', models.BinaryField(blank=True, null=True)),
                ('source', models.CharField(choices=[('human', 'Human'), ('synthetic', 'Synthetic'), ('user', 'User Generated')], default='human', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShaderGenerationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compiled_successfully', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shaderator.prompt')),
            ],
        ),
        migrations.DeleteModel(
            name='GeneratedShaderCodeView',
        ),
        migrations.RenameField(
            model_name='generatedshadercode',
            old_name='prompt',
            new_name='user_prompt',
        ),
        migrations.AddField(
            model_name='sandboxglslcorpus',
            name='prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shaderator.prompt'),
        ),
        migrations.AddField(
            model_name='shadescriptorcorpus',
            name='prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shaderator.prompt'),
        ),
    ]
