# Generated by Django 5.0.6 on 2024-08-26 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaderator', '0010_prompt_shadergenerationrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedshadercode',
            name='prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shaderator.prompt'),
        ),
    ]
