# Generated by Django 5.0.6 on 2024-08-26 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaderator', '0011_generatedshadercode_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='text',
            field=models.TextField(),
        ),
    ]
