# Generated by Django 5.0.6 on 2024-08-26 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shaderator', '0012_alter_prompt_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedshadercode',
            name='user_prompt',
        ),
        migrations.RemoveField(
            model_name='generatedshadercode',
            name='vector',
        ),
        migrations.RemoveField(
            model_name='sandboxglslcorpus',
            name='synth_prompt',
        ),
        migrations.RemoveField(
            model_name='sandboxglslcorpus',
            name='vector',
        ),
        migrations.RemoveField(
            model_name='shadescriptorcorpus',
            name='human_prompt',
        ),
        migrations.RemoveField(
            model_name='shadescriptorcorpus',
            name='vector',
        ),
    ]
