# Generated by Django 5.0.6 on 2024-08-27 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaderator', '0013_remove_generatedshadercode_user_prompt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shadescriptorcorpus',
            name='input_date',
        ),
        migrations.AlterField(
            model_name='prompt',
            name='source',
            field=models.CharField(choices=[('human', 'Human'), ('synthetic', 'Synthetic'), ('user', 'User Generated')], default='user', max_length=20),
        ),
    ]
