# Generated by Django 5.0.6 on 2024-09-01 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaderator', '0014_remove_shadescriptorcorpus_input_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='text',
            field=models.TextField(unique=True),
        ),
    ]
