# Generated by Django 5.0.6 on 2024-09-21 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaderator', '0015_alter_prompt_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShaderModelGenerationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('code', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compiled_successfully', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('attempt_number', models.IntegerField()),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shaderator.prompt')),
            ],
        ),
    ]
