# Generated by Django 5.0.6 on 2024-09-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaderator', '0016_shadermodelgenerationrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='source',
            field=models.CharField(choices=[('human', 'Human'), ('synthetic', 'Synthetic'), ('user', 'User Generated')], db_index=True, default='user', max_length=20),
        ),
    ]
